fail if tests fail

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -67,3 +67,9 @@ jobs:
         with:
           name: mochawesome-report
           path: mochawesome-report/
+      
+      - name: Fail on test errors
+      if: failure() # Warunek, który uruchomi się tylko jeśli wcześniejsze kroki zakończą się błędem
+      run: |
+        echo "Tests failed. Failing the job."
+        exit 1
