xxx

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -65,3 +65,20 @@ jobs:
       - name: Stop the app
         run: kill $(cat .pidfile)
 
+       # 10. Archive mochawesome report
+
+      - name: Archive mochawesome report
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+         name: mochawesome-report
+         path: mochawesome-report/
+
+       # 11. Fail on test errors
+
+      - name: Fail on test errors
+        if: failure() # Uruchom tylko, jeśli poprzednie kroki zakończą się błędem
+        run: |
+         echo "Tests failed. Failing the job."
+         exit 1  
+
